"""Every shelf of the two crawled shops, mapped onto our categories.

The shop's own shelf is the strongest evidence for what a product is
(`categorize`, source 1): somebody at the shop put the article there. These
tables say, once per shelf, what that shelf means in our vocabulary, so every
product on it follows: a category key, `@section` when the shelf holds several
of our categories (the name then picks among them), or None when the shelf is
not a kind of product (an offer page, a brand, "Neuheiten") or mixes sections.

Drafted by Gemini on 2026-10-09 from each shelf's name and example products,
then checked by hand: offer pages it had read as pork and sauces, a whole
department read as one category, and Mozzarella filed one way at ALDI and
another at GLOBUS were corrected. The 40 GLOBUS shelves mapped by hand earlier
stay in `categorize.SHOP_PATHS` and win over this table.

GLOBUS shelves are the last two path segments before the article in a product
URL (`frisches-obst/aepfel`); ALDI shelves are the crawl's category path
(`Käse / Reibekäse`), because ALDI's product URLs carry no shelf.
"""

from __future__ import annotations

GLOBUS: dict[str, str | None] = {
    "aufstriche/herzhafte-aufstriche": "herzhafte-aufstriche",
    "aufstriche/nuss-schokoaufstriche": "schokocreme",
    "aufstriche/sonstige-aufstriche": "@aufstriche",
    "backzutaten/backdekoration": "backzutaten-kat",
    "backzutaten/backmischungen": "backzutaten-kat",
    "backzutaten/dessertpulver": "backzutaten-kat",
    "backzutaten/klassische-backzutaten": "backzutaten-kat",
    "backzutaten/mehl": "backzutaten-kat",
    "backzutaten/zucker-suessungsmittel": "backzutaten-kat",
    "brot-backwaren-fruehstueck/aufstriche": "@aufstriche",
    "brot-backwaren-fruehstueck/brot-backwaren": "@backwaren",
    "brot-backwaren-fruehstueck/kakao": "kakao",
    "brot-backwaren-fruehstueck/meisterbaeckerei": None,
    "brot-backwaren-fruehstueck/tee": "tee",
    "brot-backwaren/backwaren": "@backwaren",
    "brot-backwaren/brot-broetchen": "@backwaren",
    "brot-backwaren/glutenfrei": None,
    "brot-backwaren/knaeckebrot-reiswaffeln-zwieback": "knaeckebrot",
    "brot-backwaren/toast-toastbroetchen": "toastbrot",
    "dudweiler/fertiggerichte": "fertiggerichte-kat",
    "fertiggerichte/fertigteig": "backzutaten-kat",
    "frisches-gemuese/erbsen-bohnen": "@gemuese",
    "frisches-gemuese/gurken": "gurken",
    "frisches-gemuese/kartoffeln": "kartoffeln",
    "frisches-gemuese/kohlgemuese-brokkoli": "@gemuese",
    "frisches-gemuese/mais": "@gemuese",
    "frisches-gemuese/paprika-chili": "paprika-chili",
    "frisches-gemuese/pilze": "pilze",
    "frisches-gemuese/salat": "salat",
    "frisches-gemuese/spargel": "@gemuese",
    "frisches-gemuese/verzehrfertiges-gemuese": "@gemuese",
    "frisches-gemuese/wurzelgemuese": "wurzelgemuese",
    "frisches-gemuese/zucchini-auberginen": "zucchini-auberginen",
    "frisches-gemuese/zwiebeln-knoblauch": "zwiebeln-knoblauch",
    "frisches-obst/aepfel": "aepfel",
    "frisches-obst/ananas": "exotisches-obst",
    "frisches-obst/bananen": "bananen",
    "frisches-obst/beeren": "beeren",
    "frisches-obst/birnen": "birnen",
    "frisches-obst/kiwis": "kiwis",
    "frisches-obst/melonen": "melonen",
    "frisches-obst/steinobst": "steinobst",
    "frisches-obst/trauben": "trauben",
    "frisches-obst/verzehrfertiges-obst": "@obst",
    "frisches-obst/zitrusfruechte": "zitrusfruechte",
    "gebaeck/feingebaeck-kekse": "kekse",
    "kaese/feta-hirtenkaese": "weichkaese",
    "kaese/frischkaese": "frischkaese",
    "kaese/grill-ofenkaese": "@kaese",
    "kaese/hartkaese": "hartkaese",
    "kaese/harzer-kaese-handkaese": "weichkaese",
    "kaese/kaesegerichte": "kaese-snacks",
    "kaese/kaesemischungen": "@kaese",
    "kaese/kaesewuerfel-snacks": "kaese-snacks",
    "kaese/mozzarella": "weichkaese",
    "kaese/parmesan": "hartkaese",
    "kaese/raclette-fonduekaese": "schnittkaese",
    "kaese/schmelz-sandwichkaese": "@kaese",
    "kaese/schnittkaese": "schnittkaese",
    "kaese/weichkaese": "weichkaese",
    "kaesetheke/frischkaese": "frischkaese",
    "kaesetheke/hartkaese": "@kaese",
    "kaesetheke/kaesesalat": "@kaese",
    "kaesetheke/schnittkaese": "schnittkaese",
    "kaesetheke/weichkaese": "weichkaese",
    "kaffee/bohnenkaffee-ganze-bohnen": "kaffee",
    "kaffee/bohnenkaffee-gemahlen": "kaffee",
    "kaffee/espresso-ganze-bohnen": "kaffee",
    "kaffee/espresso-gemahlen": "kaffee",
    "kaffee/filtertueten": "haushaltswaren",
    "kaffee/instantkaffee": "kaffee",
    "kaffee/kaffeekapseln": "kaffee",
    "kaffee/kaffeepads": "kaffee",
    "kaffee/koffeinfreier-kaffee": "kaffee",
    "kaffee/malzkaffee": "kaffee",
    "kakao/kakaopulver": "kakao",
    "kakao/trinkpulver": "kakao",
    "koerperpflege/rasur-haarentfernung": "koerperpflege-kat",
    "konserven-feinkost/instant-gerichte": "fertiggerichte-kat",
    "make-up/augen": "make-up",
    "margarine-butter-fette/butter": "butter",
    "margarine-butter-fette/butterzubereitung-kraeuterbutter": "butter",
    "margarine-butter-fette/margarine-streichfette": "butter",
    "margarine-butter-fette/schmalz": "butter",
    "margarine-butter-fette/speisefett": "butter",
    "meisterbaeckerei/kuchen-torten": "suessgebaeck",
    "meisterbaeckerei/sonstige-backwaren": "suessgebaeck",
    "milch-molkereiprodukte/buttermilch-dickmilch": "milch",
    "milch-molkereiprodukte/frische-milch": "milch",
    "milch-molkereiprodukte/fruchtjoghurts": "joghurt",
    "milch-molkereiprodukte/goetterspeise-gruetze": "desserts",
    "milch-molkereiprodukte/h-milch": "milch",
    "milch-molkereiprodukte/joghurts": "@milch-joghurt",
    "milch-molkereiprodukte/kakao-shakes-kaffee": "milchgetraenke",
    "milch-molkereiprodukte/kefir-molke": "milch",
    "milch-molkereiprodukte/milchgetraenke": "milchgetraenke",
    "milch-molkereiprodukte/milchreis-griesspudding": "desserts",
    "milch-molkereiprodukte/milchsnacks": "desserts",
    "milch-molkereiprodukte/mousse": "desserts",
    "milch-molkereiprodukte/naturjoghurts": "joghurt",
    "milch-molkereiprodukte/pudding-desserts": "desserts",
    "milch-molkereiprodukte/quarkdesserts": "quark",
    "milch-molkereiprodukte/trinkjoghurts": "joghurt",
    "milchersatz/milchersatz-cremes": "@milchersatz",
    "milchersatz/milchersatz-drinks": "pflanzendrink",
    "milchersatz/milchersatz-joghurts": "@milchersatz",
    "milchprodukte-eier/kaese": "@kaese",
    "milchprodukte-eier/kaesetheke": "@kaese",
    "milchprodukte-eier/margarine-butter-fette": "butter",
    "muesli/cornflakes-cerealien": "muesli",
    "muesli/frucht-muesliriegel": "muesliriegel",
    "muesli/muesli": "muesli",
    "nudeln-reis-getreide/getreide": "@nudeln-reis",
    "obst-gemuese/frische-kraeuter-gewuerze": "frische-kraeuter",
    "obst-gemuese/frisches-obst": "@obst",
    "obst-gemuese/trockenobst-nuesse-kerne": "@nuesse-trockenobst",
    "party-geschenke/einweggeschirr": "haushaltswaren",
    "reinigungsmittel/allzweckreiniger": "putzmittel",
    "reinigungsmittel/bad-kalkreiniger": "putzmittel",
    "reinigungsmittel/wc-reiniger-steine": "putzmittel",
    "soft-drinks/cola-limonaden": "limonade",
    "spirituosen/mixgetraenke-cocktails": "spirituosen",
    "tee/chai-latte-chai-tee": "tee",
    "tee/fruechtetee": "tee",
    "tee/gruener-tee": "tee",
    "tee/heiltee": "tee",
    "tee/instanttee": "tee",
    "tee/kraeutertee": "tee",
    "tee/rooibostee": "tee",
    "tee/schwarzer-tee": "tee",
    "tee/weisser-tee": "tee",
    "tiefkuehlprodukte/tiefkuehl-obst": None,
    "trockenobst-nuesse-kerne/kerne-nuesse-samen": "nuesse",
}

ALDI: dict[str, str | None] = {
    "Alkoholische Getränke / Alkoholfreie Weine, Biere & Spirituosen": None,
    "Alkoholische Getränke / Bier": "bier",
    "Alkoholische Getränke / Roséwein": "@wein",
    "Alkoholische Getränke / Rotwein": "rotwein",
    "Alkoholische Getränke / Sekt & Schaumwein": "sekt",
    "Alkoholische Getränke / Spirituosen": "spirituosen",
    "Alkoholische Getränke / Wein": "@wein",
    "Alkoholische Getränke / Weißwein": "weisswein",
    "Babyartikel / Babynahrung": None,
    "Babyartikel / Babypflege & Windeln": "hygiene",
    "Backwaren, Aufstriche & Cerealien / Brot": "brot",
    "Backwaren, Aufstriche & Cerealien / Brötchen & Baguette": "broetchen",
    "Backwaren, Aufstriche & Cerealien / Fertigkuchen & Süßgebäck": "suessgebaeck",
    "Backwaren, Aufstriche & Cerealien / Fruchtaufstriche & Marmelade": "marmelade",
    "Backwaren, Aufstriche & Cerealien / Herzhafter Brotaufstrich": "herzhafte-aufstriche",
    "Backwaren, Aufstriche & Cerealien / Herzhaftes Gebäck": "herzhaftes-gebaeck",
    "Backwaren, Aufstriche & Cerealien / Honig": "honig",
    "Backwaren, Aufstriche & Cerealien / Hotdogs, Burger Buns & Wraps": "@backwaren",
    "Backwaren, Aufstriche & Cerealien / Knäckebrot, Zwieback & Reiswaffeln": "knaeckebrot",
    "Backwaren, Aufstriche & Cerealien / Müsli & Cornflakes": "muesli",
    "Backwaren, Aufstriche & Cerealien / Nuss- & Schokocreme": "schokocreme",
    "Backwaren, Aufstriche & Cerealien / Toastbrot": "toastbrot",
    "Backzutaten, Mehl & Zucker / Backaromen & Backhelfer": "backzutaten-kat",
    "Backzutaten, Mehl & Zucker / Backmischungen": "backzutaten-kat",
    "Backzutaten, Mehl & Zucker / Mehl": "backzutaten-kat",
    "Backzutaten, Mehl & Zucker / Zucker & Süßungsmittel": "backzutaten-kat",
    "Bettwäsche & Heimtextilien": None,
    "Bio-Produkte": None,
    "Blumen & Blumensträuße": "blumen",
    "Dauerhaft günstig": None,
    "Drogerie & Kosmetik / Deodorant": "deo",
    "Drogerie & Kosmetik / Hand-, Fuß- & Nagelpflege": "koerperpflege-kat",
    "Drogerie & Kosmetik / Hygieneartikel": "hygiene",
    "Drogerie & Kosmetik / Körper- & Gesichtspflege": "@koerperpflege",
    "Drogerie & Kosmetik / Make-up": "make-up",
    "Drogerie & Kosmetik / Nahrungsergänzungsmittel": "nahrungsergaenzung",
    "Drogerie & Kosmetik / Rasur & Haarentfernung": "@koerperpflege",
    "Drogerie & Kosmetik / Seife": "duschgel",
    "Drogerie & Kosmetik / Shampoo & Haarpflege": "haarpflege",
    "Drogerie & Kosmetik / Zahnpflegeprodukte": "zahnpflege",
    "Einrichtung & Wohnen": None,
    "Fahrrad & Zubehör": None,
    "Fairtrade-Produkte": None,
    "Fleisch & Fisch / Bratwurst & Würstchen": "fleischwurst",
    "Fleisch & Fisch / Fisch & Meeresfrüchte": "fisch-kat",
    "Fleisch & Fisch / Geflügel": "gefluegel",
    "Fleisch & Fisch / Hackfleisch": "hackfleisch",
    "Fleisch & Fisch / Rindfleisch": "rind",
    "Fleisch & Fisch / Schweinefleisch": "schwein",
    "Garten": None,
    "Getränke / Cola": "limonade",
    "Getränke / Eistee": "limonade",
    "Getränke / Energydrinks": "limonade",
    "Getränke / Kaffee": "kaffee",
    "Getränke / Kakao-, Milch- & Kaffeegetränke": "milchgetraenke",
    "Getränke / Limonade": "limonade",
    "Getränke / Mineralwasser": "wasser",
    "Getränke / Saft, Nektar & Smoothies": "saft",
    "Getränke / Tee": "tee",
    "Griechischer Genuss": None,
    "Haushaltsartikel / Batterien": None,
    "Haushaltsartikel / Müllbeutel & Folien": "folien-beutel",
    "Haushaltsartikel / Papier & Tücher": "@papier-folien",
    "Haushaltsartikel / Putzmittel": "putzmittel",
    "Haushaltsartikel / Spülmittel & Schwämme": "spuelmittel",
    "Haushaltsartikel / Waschmittel": "waschmittel",
    "Heimwerken": None,
    "Italienischer Genuss": None,
    "Kleidung": None,
    "Konserven & Fertiggerichte / Antipasti-Feinkost & Salate": None,
    "Konserven & Fertiggerichte / Eintöpfe & Suppen": "fertiggerichte-kat",
    "Konserven & Fertiggerichte / Fertiggerichte & Ravioli": "fertiggerichte-kat",
    "Konserven & Fertiggerichte / Fischkonserven": "fisch-kat",
    "Konserven & Fertiggerichte / Gemüsekonserven": "gemuesekonserven",
    "Konserven & Fertiggerichte / Obstkonserven": "obstkonserven",
    "Konserven & Fertiggerichte / Wurst- & Fleischkonserven": None,
    "Käse / Feta & Hirtenkäse": "@kaese",
    "Käse / Frischkäse": "frischkaese",
    "Käse / Hartkäse & Stückkäse": "@kaese",
    "Käse / Mozzarella": "weichkaese",
    "Käse / Ofenkäse": "@kaese",
    "Käse / Reibekäse": "reibekaese",
    "Käse / Schmelzkäse": "@kaese",
    "Käse / Schnittkäse": "schnittkaese",
    "Käse / Weichkäse": "weichkaese",
    "Küche & Backen": "haushaltswaren",
    "Markenprodukte": None,
    "Milchprodukte & Eier / Butter & Margarine": "butter",
    "Milchprodukte & Eier / Eier": "eier-kat",
    "Milchprodukte & Eier / Fruchtjoghurt & Desserts": "@milch-joghurt",
    "Milchprodukte & Eier / Milch": "milch",
    "Milchprodukte & Eier / Naturjoghurt & Skyr": "@milch-joghurt",
    "Milchprodukte & Eier / Sahne, Schmand & Crème fraîche": "sahne",
    "Milchprodukte & Eier / Speisequark": "quark",
    "Neuheiten": None,
    "Nudeln, Reis & Hülsenfrüchte / Hülsenfrüchte & Getreide": "huelsenfruechte",
    "Nudeln, Reis & Hülsenfrüchte / Kartoffelprodukte": None,
    "Nudeln, Reis & Hülsenfrüchte / Nudeln & Pasta": "nudeln",
    "Nudeln, Reis & Hülsenfrüchte / Reis": "reis",
    "Outdoor & Freizeit": None,
    "Proteinprodukte": None,
    "Saucen, Öle & Gewürze / Brühe, Bouillons & Fonds": "bruehe",
    "Saucen, Öle & Gewürze / Dressings": "saucen",
    "Saucen, Öle & Gewürze / Essig & Öl": "oel-essig",
    "Saucen, Öle & Gewürze / Gewürze & frische Kräuter": "gewuerze",
    "Saucen, Öle & Gewürze / Mayonnaise, Ketchup & Remoulade": "saucen",
    "Saucen, Öle & Gewürze / Saucen & Fertigsaucen": "saucen",
    "Saucen, Öle & Gewürze / Senf & Meerrettich": "saucen",
    "Schreibwaren": None,
    "Spielzeug": None,
    "Sport & Fitness": None,
    "Super Saver": None,
    "Süßigkeiten & salzige Snacks / Bonbons": "bonbons",
    "Süßigkeiten & salzige Snacks / Chips & Knabbereien": "@salzige-snacks",
    "Süßigkeiten & salzige Snacks / Frucht- & Müsliriegel": "muesliriegel",
    "Süßigkeiten & salzige Snacks / Kaugummis": "bonbons",
    "Süßigkeiten & salzige Snacks / Kekse": "kekse",
    "Süßigkeiten & salzige Snacks / Lakritz & Fruchtgummi": "fruchtgummi",
    "Süßigkeiten & salzige Snacks / Nougat & Konfekt": "schokolade",
    "Süßigkeiten & salzige Snacks / Nüsse & Trockenfrüchte": "@nuesse-trockenobst",
    "Süßigkeiten & salzige Snacks / Schokolade": "schokolade",
    "Technik & Elektronik": None,
    "Tiefkühlung / Eis": "speiseeis",
    "Tiefkühlung / Pommes, Wedges & Kroketten": "tk-kartoffel",
    "Tiefkühlung / TK Desserts & Backwaren": "tk-backwaren",
    "Tiefkühlung / TK Fisch & Meeresfrüchte": "fisch-kat",
    "Tiefkühlung / TK Fleisch": "@fleisch",
    "Tiefkühlung / TK Garnelen": "fisch-kat",
    "Tiefkühlung / TK Gemüse": "tk-gemuese",
    "Tiefkühlung / TK Lachs": "fisch-kat",
    "Tiefkühlung / TK Obst": None,
    "Tiefkühlung / TK Pfannen- & Fertiggerichte": "tk-fertig",
    "Tiefkühlung / TK Pizza & Baguettes": "pizza",
    "Tierbedarf / Hundefutter": None,
    "Tierbedarf / Katzenfutter & Katzenstreu": None,
    "Vegetarisch & Vegan / Aufstriche": "herzhafte-aufstriche",
    "Vegetarisch & Vegan / Fertiggerichte": "fertiggerichte-kat",
    "Vegetarisch & Vegan / Fisch- & Fleischersatz": "fertiggerichte-kat",
    "Vegetarisch & Vegan / Joghurt- & Dessertalternativen": None,
    "Vegetarisch & Vegan / Käse- & Wurstalternativen": None,
    "Vegetarisch & Vegan / Milchalternativen": "pflanzendrink",
    "Vegetarisch & Vegan / Tiefkühlprodukte": "@tk-herzhaft",
    "Vegetarisch & Vegan / Tofu, Falafel & Gemüsebällchen": "fertiggerichte-kat",
    "Vegetarisch & Vegan / Vegane Süßigkeiten & Snacks": "@suesswaren",
    "Wochenangebote / Eigenmarken im Angebot": None,
    "Wochenangebote / Frischeprodukte im Angebot": None,
    "Wochenangebote / Markenprodukte im Angebot": None,
    "Wurst & Aufschnitt / Fleischwurst": "fleischwurst",
    "Wurst & Aufschnitt / Geflügelwurst": "gefluegelaufschnitt",
    "Wurst & Aufschnitt / Salami": "salami",
    "Wurst & Aufschnitt / Schinken": "schinken",
    "Wurst & Aufschnitt / Streichwurst & Pasteten": "fleischwurst",
    "XXL": None,
}
